### ISSUE TITLE
Beta 1.3 support?

### ISSUE THREAD

**Issue by ravngr** [equalpants/pigmap#11]
Specification for the new save format is here http://mojang.com/2011/02/16/minecraft-save-file-format-in-beta-1-3/

Any plans to update pigmap ahead of the release (or at all)?

**Comment by equalpants** [comment]
pigmap will be updated shortly after the Beta 1.3 release.

**Comment by ravngr** [comment]
Awesome, keep up the fine work :)

**Comment by Lith** [comment]
Hi, 

Do you know when a new update will be available ?

TY !

**Comment by equalpants** [comment]
Either today or tomorrow.
