### ISSUE TITLE
Pigmap doesn't find terrain.png

### ISSUE THREAD

**Issue by Masterrg** [equalpants/pigmap#15]
Command used:

pigmap -B 6 -T 1 -Z 12 -i /var/www/vhosts/xxx/private/minecraft_server/world_of_minecraft -o /var/www/vhosts/xxx/httpdocs/mapoverview -m /var/www/vhosts/xxx/httpdocs/mapoverview -h 3 -g /var/www/vhosts/xxx/private/pigmap

Result:
/var/www/vhosts/xxx/private/pigmap/blocks-6.png not found (or failed to read as PNG); will try to build from terrain.png
couldn't find terrain.png and/or fire.png
no block images available; aborting render

Well, terrain.png is there. I didn't move any files and I just used the same command that I used with your previously built.

OS: Debian 5.0

Regards

**Comment by equalpants** [comment]
Is fire.png there?  If you were using a pre-0.6 version before, there are changes; please see the changelog in the README, and the instructions for -g.

**Comment by Masterrg** [comment]
I placed the fire.png into the same folder, but it doesn't work for me.
I also tried to place it into the "." folder, but it doesn't work either.

Regards

**Comment by Masterrg** [comment]
Recompiled it 5 minutes ago, suddenly it works - thanks and sorry for the inconvenience.

Regards
