### ISSUE TITLE
Biome Tinting support

### ISSUE THREAD

**Issue by demonspork** [equalpants/pigmap#16]
I was wondering if you are planning to implement biome tinting support so that we can use the EXTRACTEDBIOMES data from the MinecraftBiomeExtractor to make an accurate depiction of the colors in the world.  That is supported in Overviewer and if I am going to switch (which I plan to do for render times) that is the one major thing holding me back.  I have a script to find the signposts manually in the map (which I already use so that I can update the signposts every 30 minutes while updating the map daily)

**Comment by equalpants** [comment]
No current plans for this, but maybe eventually.

**Comment by equalpants** [comment]
Now that biomes are stored in the world data, I'll probably do this at some point.

**Comment by demonspork** [comment]
Any progress on this?

**Comment by demonspork** [comment]
Just kidding. :)
