### ISSUE TITLE
Pigmap still has a few bugs...

### ISSUE THREAD

**Issue by Drakonas** [equalpants/pigmap#2]
When I ran pigmap, it still rendered a lot of chunks outside of the real map.

Also, pigmap did not copy template.html and style.css to the output directory, let alone change the {tileSize}, etc. to the correct value in the html file.

Do you have any input on this?

Thanks for your hard work,
Drakonas

**Comment by Drakonas** [comment]
Forget what I said. I seem to have lost track of where my fork was along the way of your updates. Disregard this issue.

Apologize for the inconvenience,
Drakonas

Closed.

**Comment by Drakonas** [comment]
Actually, it seems that it still isn't copying the template.html and editing it. Any way you could fix?

**Comment by equalpants** [comment]
Please make sure you are using -m properly.  It does indeed copy template.html correctly, as long as it can find it.

**Comment by Drakonas** [comment]
hmm...duly noted. Thanks.
