### ISSUE TITLE
Ignore baseZoom being too small

### ISSUE THREAD

**Issue by aheadley** [equalpants/pigmap#20]
Can you add an option to continue even if the baseZoom is too small, skipping chunks that would be off the edge of the map (like Minecraft-Overviewer)? A player has gone off the edge of the current map but I don't want to increase the zoom level, so pigmap is just aborting when it sees that the farthest chunks need the next higher zoom level.

You can see the issue here, on the long trail at the bottom left: http://thedailyautist.com/map/
In the "Day" (Minecraft-Overviewer) view, it just cuts off at the border, while the "Unlit" (pigmap) view hasn't been updated since the chunks just beyond that point were created.

**Comment by equalpants** [comment]
Probably not gonna add an option for this (not useful enough), but this would only take like 2 minutes to change, so if you give me your email, I'll send you a modified world.cpp.

Can I ask why you don't want to increase the baseZoom?

**Comment by aheadley** [comment]
My email is my username AT waysaboutstuff.com . I don't want to increase the baseZoom because I'm trying to keep the pigmap and Minecraft-Overviewer renders in sync and increasing the baseZoom on only pigmap would screw that up. There's also the fact that the current zoom level is fine except for that one part and that I don't really want to waste the effort of the player who walked that far to avoid having their stuff show up on the map (if that's why they did it).

**Comment by equalpants** [comment]
Huh, still don't think I understand (why not increase it for both pigmap and Overviewer?), but I'll send you that file in a little bit.
