### ISSUE TITLE
Google maps efficiency 

### ISSUE THREAD

**Issue by cookednoodles** [equalpants/pigmap#22]
My c++ is a little rusty, but from what I see you appear to be rendering a different map for each size ?

Wouldn't it be a lot faster to just render one version at the closest zoom level, even if it was just one big image. And then rescale it and cut it up for the google maps zoom levels ?

**Comment by equalpants** [comment]
It would indeed be faster to rescale the images from the closest zoom level, which is why it is already done that way.
