### ISSUE TITLE
1.9 New block

### ISSUE THREAD

**Issue by dvs13** [equalpants/pigmap#28]
subj

**Comment by jcornwellshiel** [comment]
I've begun work on the new 1.8 blocks in my fork here: https://github.com/jcornwellshiel/pigmap

It's far from perfect at the moment. Glass rotation is off, vines aren't colored, and I haven't implemented a few of the new blocks yet. It should progress over the next few days though.

**Comment by equalpants** [comment]
New blocks up to Minecraft 1.0 have been added.
