### ISSUE TITLE
New Minecraft Map Format “Anvil” and new Blocks

### ISSUE THREAD

**Issue by Masterrg** [equalpants/pigmap#31]
Pigmap isn't compatible with the new map format yet, and also new Blocks of Minecraft 1.2 are missing right now.

Regards

**Comment by sawine** [comment]
I'm also looking forward this update to 1.2.

Thanks

**Comment by equalpants** [comment]
Working on this now; should be coming soon.

**Comment by schamane** [comment]
I am also interested in this update...

**Comment by tickleman** [comment]
Very good work, waiting your update for 1.2.3 with impatience :)

**Comment by sseering** [comment]
Hi. I have something here and I am not sure if this is a bug or some result of the new map format:

I run a vanilla SMP server in the current version (1.2.3). I tried to do a full render of the world with pigmap but i get the output

```
region-format world detected
scanning world data...
nothing to do!  (no required tiles)
```

I know that pigmap can render new maps for the biggest part as it renders my singleplayer survival map. Is this a bug? Something related to the new map format?

**Comment by Masterrg** [comment]
Pigmap doesn't support Minecraft 1.2.3 yet - equalpants is working on an update.

If you let pigmap run over a "to 1.2.3 converted" map, the mapfolder still contains the files of the old map format, so it may looks like it renders the new map, but this is false.

**Comment by nbsparks** [comment]
Equalpants,

Is there any way with this new anvil format that you can choose to ignore the top crust layers of the nether worlds and map those too?  In the current 1.1 compatible pigmap, the maps of nether worlds are not viable.

Just an idea!  Thanks for all that you do!

**Comment by FibreFoX** [comment]
any progress on this update?

**Comment by equalpants** [comment]
Anvil support has been added in pigmap 1.1, along with the new blocks up to Minecraft 1.2.4.

sbhouse: there are new command line options for choosing which range of Y-values to render, so those should help with nether rendering.
