### ISSUE TITLE
Problem with Incremental Update (pigmap.params)

### ISSUE THREAD

**Issue by Masterrg** [equalpants/pigmap#32]
Right now, I can't run an incremental update, always the error "can't find pigmap.params in output path" occures.

Of course a normal rendering was running before, but the pigmap.params has not been generated automatically.
I've tried to check the outputpath variable you use in pigmap.ccp and it points me directly into my output directory.

I created the file "pigmap.params" in my outputfolder, put the used parameters in it, but the error still occures and the file doesn't get recognized.

OS: Debian 6.0 x64

Regards

**Comment by equalpants** [comment]
Whoops, sorry about that!  Can't believe I completely forgot to test this one piece of new code.

Fixed in version 1.1.1.

**Comment by equalpants** [comment]
Did you rebuild?

Is there in face a pigmap.params in the output path?  If so, can you send it to me?

I think you mentioned manually editing it before--it's not really meant to be human-editable, so the formatting is pretty unforgiving.  In particular, if there are blank lines, or extra spaces, that might mess things up.

Michael Nelson
yep.

**Comment by Masterrg** [comment]
Yes I did a rebuild. The problem was a missing terrain.png because I erased the old folder of pigmap and rebuild it in a new folder.

But this still sounds like a smaller bug, if it throws a "pigmap.params is missing"-error if the terrain.png is missing. I just added it and pigmap started an incremental build as it should.

Regards
