### ISSUE TITLE
New pigmap not rendering correctly

### ISSUE THREAD

**Issue by jmirmina** [equalpants/pigmap#33]
Before upgrading to the new Pigmap that supported the Anvil file format, I completely removed my old pigmap. I installed the new Pigmap on Mineos, ran it, and it generated the Nether correctly, however, it did not generate my main world. The only directories generated in the /world folder were /0 and /DIM-1.

When I attempt to run it again, it renders on the same number of base tiles as it did when I ran it a few minutes before (not for the nether, however).

**Comment by equalpants** [comment]
Please supply the command line you used and the console output.

Thanks,

Michael Nelson
yep.

**Comment by jmirmina** [comment]
I apologize. It seems to be an issue with MineOS. I tried running pigmap directly instead of through the MineOS console, and it seems to work correctly.
