### ISSUE TITLE
Problem with slabs and reversed stairs

### ISSUE THREAD

**Issue by Masterrg** [equalpants/pigmap#34]
Placed slabs and reversed stairs of every kind were just rendered as slabs (id: 44 / meta: 0).

**Comment by equalpants** [comment]
Slabs and reversed stairs seem to be working just fine.  Can you provide an offending tile image, and the region it was generated from?

**Comment by Masterrg** [comment]
What it looks like ingame: www.worldofminecraft.eu/download/pigmap/1.png
And on the Livemap: www.worldofminecraft.eu/download/pigmap/2.png

Erase that with reversed stairs, i missunderstood the bugreport of the user, but it looks like a "reversed" slab ingame: Normally the slab gets attached to the bottom of the place, those are attached to the top. I'll ask the user how he has done it, maybe it's some kind of glitch or bug in Minecraft.

Regards

**Comment by Masterrg** [comment]
Well, it's a feature of 1.2: Just click on the downside of a block, to place the slab directly under it.

**Comment by damopewpew** [comment]
Also some of the slabs with different meta ids get rendered as stone slab, for instance sandstone slabs

**Comment by equalpants** [comment]
Huh, cool--guess I missed that completely!  Thanks for spotting it, I'll add those in pretty soon.

Michael Nelson
yep.

**Comment by damopewpew** [comment]
Also just in case you're not aware the upside slabs also can be done with stairs :)

**Comment by equalpants** [comment]
Okay, inverted slabs are added with version 1.1.2.
