### ISSUE TITLE
baseZoom too small!

### ISSUE THREAD

**Issue by Ahava** [equalpants/pigmap#36]
Hello,

my map is very big and I tried to render it with pigmap. But it tells me every time that the baseZoom is too small even if I try to render with "-B 16 -T 1".

Is there any way to increase the baseZoom or  to ignore that the baseZoom is too small?

grettings

**Comment by equalpants** [comment]
The -B parameter controls the level of detail at the highest zoom; it's -Z which controls the baseZoom.  Or you can leave it out to have pigmap choose automatically.

Can you provide the exact command line you're using, and the full console output?

**Comment by Ahava** [comment]
./pigmap -i /home/mc/smp/world -o ./out -g ./images -h 3 -B 16 -T 1 -Z 1
region-format world detected
scanning world data...
baseZoom too small!  can't fit tile [576,-32]

**Comment by equalpants** [comment]
Your baseZoom (-Z) is 1, which is indeed quite small.  Increasing it will work, or you can leave -Z out entirely to have pigmap automatically choose it for you, which is probably easiest.  (More details are in the README.)
