### ISSUE TITLE
pigmap doesnt find images

### ISSUE THREAD

**Issue by pete52** [equalpants/pigmap#38]
Hi,

the console output looks like this:

mc@666:~/pigmap$ ls *.png
endportal.png  fire.png  terrain.png

mc@666:~/pigmap$ ./pigmap -B 6 -T 1 -Z 10 -i ../World -o output/ -h 3
./blocks-6.png not found (or failed to read as PNG); will try to build from terrain.png
image path is missing at least one of: terrain.png, fire.png, endportal.png
no block images available; aborting render

From what I could read from the source, I would suspect an issue with libpng. Since I am not fond at all with.. well libpng...
would you create a simple test program that contains a simple libpng call to see what the problem might be?

I tried:
# include iostream      // had to remove the < > here because github does something weird with them
# include png.h          // same here
# include "rgba.h"

using namespace std;

main() {
const RGBAImage terrain;
cout << terrain.readPNG("/home/mc/pigmap/terrain.png"); }

But I am only getting obscure compilation errors, probably due to me trying to use readPNG the wrong way

**Comment by equalpants** [comment]
The error message is telling you what the problem is:
"image path is missing at least one of: terrain.png, fire.png, endportal.png"
Please see the image path (-g) section of the README.

**Comment by pete52** [comment]
I did read that and it says the -g parameter may be omited to use the current directory, which as you can see by the "ls" command up above, contains all 3 required png files

**Comment by equalpants** [comment]
Whoops, my bad.  Are they all RGBA?  If one of them is merely RGB then it will be rejected.  (I need to either drop that restriction or mention it in the README.)

**Comment by pete52** [comment]
Ah! that helped. Turns out the fire.png from the faithful32 pack is only 24bit (RGB), so I used the one pigmap comes with and now its "running threads" :) thanks
