### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by pjt0620** [equalpants/pigmap#7]
when i try to load the web page i get a blank screen http://67.222.152.118/index.html i have the image png files for the map am i missing something i have the default files on the github

**Comment by equalpants** [comment]
That page wasn't generated by pigmap.  Sorry, but this isn't the place for general HTML/JavaScript lessons--if you want to make your own thing by manually copying and editing template.html, that's great, but I can't do your debugging for you.  However, I will point out a couple things I noticed:
1. You appear to be trying to use "." at the start of a URL to mean "the current directory".  I don't know a lot about web programming, but I think that might be frowned upon.  Try providing an absolute URL instead.
2. The map image files do not appear to actually be on your server, or at least not in the same directory as index.html.  (That is, http://67.222.152.118/base.png doesn't go anywhere.)

**Comment by pjt0620** [comment]
thank you so much I was doing this at 2 in the morning.  After i read your response this morning I found that i had two problems one was a bad map copy and the other was a bad set so setup instructions
